"""bookings

Revision ID: 94b5562083f7
Revises: d440f2c727f6
Create Date: 2026-05-10 03:46:58.343775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b5562083f7'
down_revision: Union[str, Sequence[str], None] = 'd440f2c727f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('consumer_user_id', sa.String(length=36), nullable=False),
    sa.Column('offering_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consumer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_consumer_user_id'), 'bookings', ['consumer_user_id'], unique=False)
    op.create_index(op.f('ix_bookings_offering_id'), 'bookings', ['offering_id'], unique=False)
    op.create_index(op.f('ix_bookings_worker_id'), 'bookings', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_worker_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_offering_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_consumer_user_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
