"""heartbeats

Revision ID: d440f2c727f6
Revises: b7784fb3025e
Create Date: 2026-05-10 03:45:09.021250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd440f2c727f6'
down_revision: Union[str, Sequence[str], None] = 'b7784fb3025e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heartbeats',
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('cpu_pct', sa.Float(), nullable=False),
    sa.Column('mem_pct', sa.Float(), nullable=False),
    sa.Column('gpu_pct', sa.Float(), nullable=True),
    sa.Column('free_ram_gb', sa.Float(), nullable=True),
    sa.Column('model_loaded_id', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heartbeats_worker_id'), 'heartbeats', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heartbeats_worker_id'), table_name='heartbeats')
    op.drop_table('heartbeats')
    # ### end Alembic commands ###
